specs:
  command_topic: '/actor/keyboard/cmd_vel'
  message: "
             Reading from the keyboard  and Publishing to Twist!
             ---------------------------
             Moving around:
               u    i    o
               j    k    l
               m    ,    .

               i/, : up/down
               k: straight
               u/o: rotate in yaw
               j/l: roll

             Publish on topics:
               g: /fsm/go_topic
               f: /fsm/overtake_topic

             Service call:
               e: /enable_motors"
  speed: 0.5
  turn: 1.0
  rate_fps: 20
  moveBindings:
    k:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    i:
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    ',':
    - 0
    - 0
    - -1
    - 0
    - 0
    - 0
    u:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 1
    o:
    - 1
    - 0
    - 0
    - 0
    - 0
    - -1
    j:
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    l:
    - 0
    - -1
    - 0
    - 0
    - 0
    - 0
  topicBindings:
    g: '/fsm/go_topic'
    f: '/fsm/overtake_topic'
  serviceBindings:
    - key: e
      name: enable_motors
      type: EnableMotors
      message: True
