output_path: /esat/opal/kkelchte/experimental_data/cube_world_fresh
mode: 4  # dag data_collection mode
job_configs:
  - command: python3.8 src/scripts/interactive_experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 10
    gpus: 1
    cpu_mem_gb: 17
    disk_mem_gb: 52
    nice: False
    gpu_mem_mb: 1900
    use_singularity: True
    check_if_ros_already_in_use: False
    save_locally: True
  - command: python3.8 src/scripts/data_cleaning.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 2
    gpus: 0
    cpu_mem_gb: 25
    disk_mem_gb: 52
    nice: False
    use_singularity: False
    check_if_ros_already_in_use: False
    save_locally: False
number_of_jobs:
  - 3
  - 1
base_config_files:
  - src/scripts/config/il_data_collection_cube_world.yml
  - src/scripts/config/data_cleaning_config.yml