output_path: parameter_study/loss
mode: loss_study
number_of_jobs:  # indicates number of seeds per parameter value
  - 3
base_config_files:
  - src/scripts/config/rl_cart_pole_vpg.yml
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 7
    gpus: 1
    cpu_mem_gb: 25
    disk_mem_gb: 52
    wall_time_s: 30 * 60 * 60
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true