output_path: /esat/opal/kkelchte/experimental_data/cube_world
mode: 1  # train_model mode
job_configs:
  - command: python3.7 src/scripts/dataset_experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 8
    gpus: 1
    cpu_mem_gb: 10
    disk_mem_gb: 52
    nice: False
    gpu_mem_mb: 4500
    use_singularity: False
    check_if_ros_already_in_use: False
    save_locally: False
number_of_jobs:
  - 3
base_config_files:
  - src/scripts/config/training_config.yml