output_path: line_world/dronet_sidetuned/adam_lr001
#output_path: line_world/dronet_finetuned/adam_lr001
mode: train
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 4
    gpus: 1
    cpu_mem_gb: 10
    disk_mem_gb: 52
    wall_time_s: 60 * 60
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
number_of_jobs:
  - 1
base_config_files:
  - src/scripts/config/il_sidetune_dronet_real_sim_noisy_augm_data.yml
#  - src/scripts/config/il_finetune_dronet_real_sim_noisy_augm_data.yml