output_path: cube_world
mode: train
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 8
    gpus: 1
    cpu_mem_gb: 10
    disk_mem_gb: 52
    wall_time_s: 60 * 60 * 2
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
number_of_jobs:
  - 3
base_config_files:
  - src/scripts/config/il_train_cube_world.yml