output_path: discrete-dummy-tracking/baseline
mode: default
number_of_jobs:  # indicates number of seeds per parameter value
  - 1
base_config_files:
  - src/scripts/config/discrete_dummy_tracking_ppo.yml
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: ~/code/imitation-learning-codebase
    cpus: 2
    gpus: 0
    cpu_mem_gb: 5
    disk_mem_gb: 52
    wall_time_s: 2 * 60 * 60
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
