output_path: line_world_decoders
mode: train_task_decoders
wait_time_between_jobs_sec: 3
job_configs:
  - command: python3.8 src/scripts/train_decoders_on_pretrained_features.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 4
    gpus: 1
    cpu_mem_gb: 15
    disk_mem_gb: 52
    wall_time_s: 3 * 60 * 60
    nice: true
    use_singularity: false
    check_if_ros_already_in_use: true
    save_locally: false
    extra_requirements: ( Has_ssse3 == True )
number_of_jobs:
  - 1
base_config_files: 
    - ''
