output_path: /esat/opal/kkelchte/experimental_data/cube_world
mode: 0  # data_collection mode
job_configs:
  - command: python3.7 src/scripts/interactive_experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 4
    gpus: 1
    cpu_mem_gb: 17
    disk_mem_gb: 52
    nice: False
    gpu_mem_mb: 1900
    use_singularity: True
    check_if_ros_already_in_use: False
    save_locally: False
number_of_jobs:
  - 3
base_config_files:
  - src/scripts/config/data_collection_config.yml