output_path: /esat/opal/kkelchte/experimental_data/cube_world
mode: data_collection
job_configs:
  - command: python src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 11
    gpus: 0
    cpu_mem_gb: 25
    disk_mem_gb: 52
    wall_time_s: 60 * 60
    nice: false
    use_singularity: true
    check_if_ros_already_in_use: false
    save_locally: true
number_of_jobs:
  - 3
base_config_files:
  - src/scripts/config/il_data_collection_cube_world.yml