output_path: line_world_mixed
mode: data_collection_line_world
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 11
    gpus: 0
    cpu_mem_gb: 25
    disk_mem_gb: 52
    wall_time_s: 15 * 60
    nice: true
    use_singularity: true
    check_if_ros_already_in_use: true
    save_locally: true
    extra_requirements: ( Mips >= 26000 )
number_of_jobs:
  - 300
  - 1
  - 3
  - 3
base_config_files:
  - src/scripts/config/il_data_collection_line_world.yml