max_duration: 100
starting_height: 0
delay_evaluation: 3
goal:
  x:
    min: 10
    max: 11
  y:
    min: 10
    max: 11
  z:
    min: 0
    max: 2
waypoints:
  - 0, 5
  - 5, 5
  - 11, 5
  - 11, 11
waypoint_reached_distance: 0.2