max_duration: -1
starting_height: 0
delay_evaluation: 3
goal:
  x:
    min: 1.7
    max: 2.2
  y:
    min: 1.7
    max: 2.2
  z:
    min: 0
    max: 1
waypoints:
  - 0, 1
  - 1, 1
  - 1, 2
  - 2, 2
waypoint_reached_distance: 0.2