supervision_topic: '/control_mapper/supervision'
rate_fps: 100
mapping:
  Unknown:
    command: '/actor/keyboard/cmd_vel'
  Terminated:
    command: '/actor/keyboard/cmd_vel'
  Running:
    command: '/actor/ros_expert/cmd_vel'
    supervision: '/actor/keyboard/cmd_vel'
  TakeOff:
    command: '/actor/ros_expert/cmd_vel'
    supervision: '/actor/keyboard/cmd_vel'
  TakenOver:
    command: '/actor/keyboard/cmd_vel'
  DriveBack: {}