supervision_topic: '/control_mapper/supervision'
mapping:
  Running:
    command: '/actor/ros_expert'
    supervision: '/actor/neural_network'
  TakeOff:
    command: '/actor/ros_expert'
  TakenOver:
    command: '/actor/keyboard'
  DriveBack:
    command: '/actor/drive_back'


#max_time
#current_time
#control_time
#aggressiveness