supervision_topic: '/control_mapper/supervision'
mapping:
  Unknown: {}
  Terminated: {}
  Running:
    command: '/actor/keyboard/cmd_vel'
  TakeOff:
    command: '/actor/keyboard/cmd_vel'
  TakenOver: {}
  DriveBack: {}