output_path: '/esat/opal/kkelchte/test_experiments/data_collection'
runner_config:
  environment_config:
    factory_key: 1 # Gym = 0, Gazebo = 1, Real = 2
    robot_name: 'turtle'
    world_name: 'esat'
    max_number_of_steps: 100
  actor_config:
    actor_type: 1 # Model = 0, Expert = 1
    description: 'default-expert'
  number_of_episodes: 2
data_saver_config:
  saving_directory: 'dataset'
  sensors:
    - 0
    - 1