output_path: test_discrete_tracking
number_of_epochs: 1000
episode_runner_config:
  number_of_episodes: 5
  train_every_n_steps: -1
architecture_config:
  architecture: discrete_tracking_actor_critic
  device: cpu
  log_std: 0
  random_seed: 5100
  initialisation_type: orthogonal
environment_config:
  normalize_observations: false
  normalize_rewards: false
  invert_reward: false
  factory_key: GYM
  gym_config:
    random_seed: 5100
    render: false
    world_name: tracking-v0
    args: 'random_location=True'
  max_number_of_steps: 300  # let number of steps depend on environment
data_saver_config:
  clear_buffer_before_episode: true
  store_on_ram_only: true
save_checkpoint_every_n: 100
tb_render_every_n_epochs: 100
tensorboard: true
run_test_episodes: true
trainer_config:
  scheduler_config:
    number_of_epochs: 1000
  criterion: MSELoss
  critic_learning_rate: 0.00005
  actor_learning_rate: 0.0001
  gradient_clip_norm: 10
  optimizer: RMSprop
  data_loader_config:
    batch_size: 200
    random_seed: 5100
  device: cpu
  discount: 0.99
  factory_key: PPO
  gae_lambda: 0.95
  phi_key: gae
  entropy_coefficient: 0.05
  max_actor_training_iterations: 50
  max_critic_training_iterations: 10
  epsilon: 0.2
  kl_target: 0.01
  use_kl_stop: false
