output_path: /esat/opal/kkelchte/experimental_data/cube_world
runner_config:
  environment_config:
    factory_key: 0
    max_number_of_steps: -1
    ros_config:
      step_rate_fps: 2
      ros_launch_config:
        control_mapping: true
        control_mapping_config: evaluation
        fsm: true
        fsm_config: single_run
        gazebo: true
        random_seed: 123
        robot_name: turtlebot_sim
        waypoint_indicator: true
        world_name: cube_world
        x_pos: 0.0
        y_pos: 0.0
        yaw_or: 1.57
        z_pos: 0.0
      visible_xterm: true
    actor_configs:
      - file: src/sim/ros/config/actor/dnn_actor.yml
        name: dnn_actor
        type: 0
      - file: src/sim/ros/config/actor/ros_expert.yml
        name: ros_expert
        type: 1
  number_of_episodes: 2
data_saver_config: {}