output_path: object_world
number_of_epochs: 1
number_of_episodes: 100
environment_config:
  factory_key: ROS
  max_number_of_steps: 1000
  ros_config:
    observation: depth_scan
    store_action: true
    store_reward: true
    visible_xterm: false
    step_rate_fps: 30
    max_update_wait_period_s: 30
    ros_launch_config:
      random_seed: 123
      robot_name: turtlebot_sim
      fsm_config: single_run
      fsm: true
      control_mapping: true
      waypoint_indicator: true
      control_mapping_config: default
      world_name: object_world
      x_pos: 0.0
      y_pos: 0.0
      z_pos: 0.0
      yaw_or: 1.57
      gazebo: true
    actor_configs:
      - name: ros_expert
        file: src/sim/ros/config/actor/ros_expert_noisy.yml
data_saver_config:
  training_validation_split: 0.9
  store_hdf5: false
  separate_raw_data_runs: true
  saving_directory_tag: expert