output_path: line_world_real
data_saver_config:
  training_validation_split: 0.7
  store_hdf5: true
  subsample_hdf5: 4
  store_on_ram_only: false
input_size: [1, 200, 200]
data_directories:
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_bluecable/raw_data/20-07-24_11-22-29_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_bluecable/raw_data/20-07-24_11-25-09_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_bluecable/raw_data/20-07-24_11-27-07_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_bluecable/raw_data/20-07-24_11-27-38_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_orangecable/raw_data/20-07-24_11-34-26_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_orangecable/raw_data/20-07-24_12-03-48_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_orangecable/raw_data/20-07-24_12-06-10_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_whitecable/raw_data/20-07-24_11-16-03_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_whitecable/raw_data/20-07-24_11-17-13_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_whitecable/raw_data/20-07-24_11-17-54_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_whitecable/raw_data/20-07-24_11-19-16_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/concrete_whitecable/raw_data/20-07-24_11-19-52_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_bluecable/raw_data/20-07-24_11-29-05_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_bluecable/raw_data/20-07-24_11-29-46_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_bluecable/raw_data/20-07-24_11-30-21_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_bluecable/raw_data/20-07-24_11-30-59_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_orangecable/raw_data/20-07-24_12-07-09_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_orangecable/raw_data/20-07-24_12-09-19_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_orangecable/raw_data/20-07-24_12-09-59_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_orangecable/raw_data/20-07-24_12-10-46_joystick
  - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_real2/grass_orangecable/raw_data/20-07-24_12-11-20_joystick