output_path: line_world
number_of_epochs: 1
number_of_episodes: 1
architecture_config:
  architecture: tiny_128_rgb_6c
  load_checkpoint_dir: /home/klaas/seed_5100
  device: cpu
environment_config:
  factory_key: ROS
  max_number_of_steps: -1
  ros_config:
    info:
      -current_waypoint
      -sensor/odometry
    observation: forward_camera
    visible_xterm: true
    step_rate_fps: 100
    ros_launch_config:
      random_seed: 123
      robot_name: bebop_real
      robot_display: true
      fsm_config: takeover_run
      fsm: true
      control_mapping: true
      waypoint_indicator: false
      control_mapping_config: takeover
      world_name: empty
      x_pos: 0.0
      y_pos: 0.0
      z_pos: 1.0
      yaw_or: 1.57
      gazebo: false
    actor_configs:
        - name: keyboard
          file: src/sim/ros/config/actor/keyboard_bebop_real.yml
data_saver_config:
  store_hdf5: false
  separate_raw_data_runs: true
  saving_directory_tag: evaluate