output_path: line_world/dronet_finetuned/real
number_of_epochs: 31
number_of_episodes: -1
save_checkpoint_every_n: 10
load_checkpoint_dir: dronet
architecture_config:
  architecture: dronet
  initialisation_type: xavier
  random_seed: 123
  device: cpu
  weight_decay: default
  dropout: default
  dtype: default
  log_std: default
  finetune: true
trainer_config:
  optimizer: SGD
  learning_rate: 0.01
  factory_key: BASE
  data_loader_config:
    hdf5_files:
    - line_world_data/real/train.hdf5
    #- /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_data/sim/line_world_sim_dronet.hdf5
    #- /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_data/sim/line_world_sim_dronet_augmented.hdf5
    #- /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_data/sim/line_world_sim_dronet_noise_augmented.hdf5
    input_size: [1, 200, 200]
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cuda
evaluator_config:
  data_loader_config:
    input_size: [1, 200, 200]
    hdf5_files:
    - /home/klaas/code/imitation-learning-codebase/experimental_data/line_world_data/real/validation.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cpu
tensorboard: true