output_path: test_encoder_decoder
number_of_epochs: 500
number_of_episodes: -1
save_checkpoint_every_n: 10
architecture_config:
  architecture: encoder_decoder_line_world_small
  initialisation_type: xavier
  random_seed: 4
  device: cuda
  dropout: default
  batch_normalisation: true
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.01
  factory_key: BASE
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
      #- /Users/kelchtermans/code/imitation-learning-codebase/experimental_data/test_line_world_mixed/clean_10/train_0.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/clean/1_64_64/train_0.hdf5
      #- /gluster/visics/kkelchte/line_world_data/sim/noisy/1_64_64/train_0.hdf5
      #- /gluster/visics/kkelchte/line_world_data/sim/noisy/1_64_64/train_1.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 128
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    hdf5_files:
      #- /Users/kelchtermans/code/imitation-learning-codebase/experimental_data/test_line_world_mixed/clean_10/validation_0.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/clean/1_64_64/validation_0.hdf5
      #- /gluster/visics/kkelchte/line_world_data/sim/noisy/1_64_64/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 128
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
tensorboard: true
