output_path: test_encoder_decoder
number_of_epochs: 500
number_of_episodes: -1
save_checkpoint_every_n: 100
architecture_config:
  architecture: encoder_decoder_line_world_small
  initialisation_type: xavier
  random_seed: 4
  device: cpu
  dropout: default
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.001
  factory_key: BASE
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
    - line_world_mixed/hdf5_files/1_64_64/train_0.hdf5
    - line_world_mixed/hdf5_files/1_64_64/train_1.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    hdf5_files:
    - line_world_mixed/hdf5_files/1_64_64/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
tensorboard: true
