output_path: test_line_world_mixed_clean
number_of_epochs: 4000
number_of_episodes: -1
save_checkpoint_every_n: 1000
architecture_config:
  architecture: encoder_decoder_line_world
  initialisation_type: xavier
  random_seed: 123
  device: cpu
  weight_decay: default
  dropout: default
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.00001
  gradient_clip_norm: 3
  factory_key: BASE
  data_loader_config:
    hdf5_files:
    - test_line_world_mixed_clean/train_0.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 1
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    hdf5_files:
    - test_line_world_mixed_clean/validation_0.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 1
  criterion: MSELoss
  device: cpu
  store_output_on_tensorboard: true
tensorboard: true