architecture_config:
  architecture: humanoid_376_17c
  device: cpu
  #load_checkpoint_dir: humanoid-v2/implmatters
data_saver_config:
  clear_buffer_before_episode: false
  store_on_ram_only: false
environment_config:
  normalize_observations: true
  normalize_rewards: true
  factory_key: GYM
  gym_config:
    random_seed: 123
    render: true
    world_name: Humanoid-v2
  max_number_of_steps: -1
number_of_episodes: 10
number_of_epochs: 1
output_path: humanoid-v2/evaluated
tensorboard: false
train_every_n_steps: 1000