output_path: /esat/opal/kkelchte/experimental_data/cube_world
generate_new_output_path: True
model_config:
  architecture: tiny_net_v0
  device: 'gpu'
  initialisation_seed: 123
trainer_config:
  criterion: 'MSELoss'
  batch_size: 64
  optimizer: 'Adadelta'
  learning_rate: 0.001
  save_checkpoint_every_n: 10
  data_loader_config:
    data_sampling_seed: 123
    balance_targets: True
    hdf5_file: train.hdf5
    inputs: # Order needs to be the same as network input (!)
      - forward_camera
#      - current_waypoint
    outputs:
      - ros_expert
#      - depth_scan
evaluator_config:
  criterion: 'MSELoss'
  data_loader_config:
    hdf5_file: validation.hdf5
    inputs:
      - forward_camera
#      - current_waypoint
    outputs:
      - ros_expert
#      - depth_scan
number_of_epochs: 30
