specs:
  command_topic: '/actor/dnn_actor/cmd_vel'
  rate_fps: 20
  model_config:
    architecture: tiny_net_v0
    load_checkpoint_dir: '/esat/opal/kkelchte/experimental_data/cube_world_all/models/seed_5100'