specs:
  command_topic: '/actor/ros_expert/cmd_vel'
  field_of_view: 100
  front_width: 40
  speed: 0.2
  noise:
    name: OUNoise
    args:
      dimension:
        - 6
        - 1
      seed: 1234
      mean: 0
      std: 0.15
      pullback: 0.2
  aggressiveness: 0
  collision_avoidance_weight: 0.0
  waypoint_following_weight: 1
  waypoint_reached_distance: 0.2
  max_yaw_deviation_waypoint: 5
  rate_fps: 20