command_topic: '/bebop/cmd_vel'
sensors:
  - 'forward_camera'
forward_camera_topic: bebop/image_raw
forward_camera_type: 'Image'
forward_camera_stats:
  height: 128
  width: 128
  depth: 3
pose_estimation_topic: /odom
pose_estimation_type: Odometry
takeoff: /bebop/takeoff
land: /bebop/land
emergency: /bebop/emergency
flattrim: /bebop/flattrim
aggressiveness: 1