robot_type: quadrotor_sim
takeoff_action: /action/takeoff
command_topic: /cmd_vel
sensors:
  - forward_camera
  - odometry
forward_camera_topic: /forward/camera/image
forward_camera_type: Image
forward_camera_stats:
  height: 200
  width: 200
  depth: 3
#imu_topic: /raw_imu
#imu_type: Imu
odometry_topic: /ground_truth/state
odometry_type: Odometry
wrench_topic: /command/wrench