# Used by test_fsm
command_topic: /cmd_vel
sensors:
  - odometry
  - modified_state
  - depth_scan
depth_scan_topic: /scan
depth_scan_type: LaserScan
depth_scan_stats:
  field_of_view: 120
  num_smooth_bins: 4
  max_depth: 4
  min_depth: 0.1
odometry_topic: /odom
odometry_type: Odometry
modified_state_topic: /modified_state
modified_state_type: CombinedGlobalPoses